name: Extend PythonAnywhere WebApp

on:
  schedule:
    - cron: '0 0 1,15 * *'
  workflow_dispatch:

jobs:
  extend-app:
    name: extend-account - ${{ matrix.account.username }}    
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        index: [1, 2, 3, 4, 5, 6]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright
          playwright install chromium --with-deps

      - name: Run Extension Script
        env:
          PA_USERNAME: ${{ secrets[format('PA_USERNAME_{0}', matrix.index)] }}
          PA_PASSWORD: ${{ secrets[format('PA_PASSWORD_{0}', matrix.index)] }}
        run: python extend_pythonanywhere.py